### PR TITLE
Fix raw matrix search for iceing

### PR DESCRIPTION
**Pull request by konrad**
Without this fix no raw matrix is found. The command finishes but does not perform the iceing. Furthermore, "*$bsize*" is not precise enough. E.g. if you have binsizes of 10000 and 100000 the current find command will find the matrix from 10000 and 100000 if the search for 10000 is done as "10000" is a substring of "100000".

### CODE REVIEW

**Comment by konrad** [comment]
Added some fixes/improvements regarding the Singularity image building.

**Comment by nservant** [comment]
Hi Konrad,
Thanks for the pull request. 
As there is not that many changes, I may merge by hand with the devel branch of HiC-Pro.
I hope to release a new version this summer.
Best

**Comment by konrad** [comment]
Thanks, @nservant!

**Comment by nservant** [comment]
Hi Konrad,
I have included your comments in the devel branch.
I close the pull request.

**Comment by konrad** [comment]
Many thanks, @nservant!

**Pull request closed without merging**
