### PR TITLE
FIX ice is now picked up globally and not locally

### PR DESCRIPTION
**Pull request by NelleV**
The following lines caused a problem when the user upgraded iced outside of HiC-pro. HiC-pro was still using the `ice` script corresponding to an old version of the `iced` python package. The following change "just" rely on using the installed version of `ice` in the user's path rather than on a local version provided by HiC-pro. As a result the `ice` script used is always the one that is associated with the `iced` package installed.

### CODE REVIEW

**Comment by NelleV** [comment]
This PR is against `master`. Let me know if I should use `devel` instead.

**Comment by nservant** [comment]
Hi Nelle,
Does it mean that I can remove the ice script from HiC-Pro scripts folder ?

**Comment by NelleV** [comment]
Yes : I'll update the installation procedure as well.

**Comment by NelleV** [comment]
Are tests being ran automatically? I thought a while back you had set up travis. If it's not the case, we should probably do that.

**Comment by nservant** [comment]
ok. Note that we will release a new version in the coming days (with python3 support) which does not install iced anymore but just ask it as a per-requisite

**Comment by nservant** [comment]
no continuous integration is  not done so far ... but indeed it would be good

**Comment by NelleV** [comment]
That's awesome! That would solve the issue we have on our server!

**Comment by nservant** [comment]
ok. I will merge and include the change in the verison I just release to avoir confusion ...
it's ok for you ?

**Comment by NelleV** [comment]
Sounds good to me!

**Pull request merged**
